name: Google Play Alpha

on: 
  workflow_dispatch:
    inputs:
      config:
        description: 'Build config'     
        required: true
        default: 'release' 
        type: choice
        options:
        - debug
        - release
      flavor:
        description: 'Flavor'
        required: true 
        type: choice
        options:
        - qa1
        - prod

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build-and-publish
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          GOOGLE_PLAY_ANDROID_DEVELOPER_BASE64: ${{ secrets.GOOGLE_PLAY_ANDROID_DEVELOPER_BASE64 }}
          GRADLE_CACHE_USERNAME: ${{ secrets.GRADLE_CACHE_USERNAME }}
          GRADLE_CACHE_PASSWORD: ${{ secrets.GRADLE_CACHE_PASSWORD }}
          RELEASE_JOB: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHANGELOG: ${{ github.event.client_payload.changelog }}
        run: |
          echo $KEYSTORE_BASE64 | base64 --decode > keystores/release.keystore
          echo $GOOGLE_PLAY_ANDROID_DEVELOPER_BASE64 | base64 --decode > keystores/google-play-android-developer.json
          ./gradlew generateChangelog -s
          ./gradlew publishProductionIntegrationsReleaseBundle -Ptrack=alpha -PreleaseStatus=completed -s
